pipeline:
    name: order
    identifier: order
    projectIdentifier: core_team
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: rngit4
                build: <+input>
    stages:
        - stage:
              name: build
              identifier: build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.gcpsalescidemo
                          namespace: build
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: test
                                identifier: test
                                spec:
                                    connectorRef: account.Harness_Docker_Connector
                                    image: ubuntu:latest
                                    command: echo echo
