JAVA_OPTS: "-Dsumo.url=https://endpoint3.collection.us2.sumologic.com/receiver/v1/http/ZaVnC4dhaV20o1LSh9W0xvxdHlY6K_s3pV1lMTKIYgQv2KnIAzCfNZSeYt0oIXeCpSQfe3cywmauNJJN6PxGHeE_tJY7DMSiqoVzVmtuplj0gbXTDJcfFA== -Delk_url=https://elk6.dev.harness.io/integration-test/_doc"
CATALINA_OPTS: "-javaagent:/usr/local/AppServerAgent-4.3.8.0/javaagent.jar -Dappdynamics.agent.nodeName=$(hostname)"
APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: <+pipeline.stages.K8_Canary.spec.serviceConfig.serviceDefinition.spec.variables.APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY>
APPDYNAMICS_AGENT_ACCOUNT_NAME: "harness-test"
APPDYNAMICS_AGENT_APPLICATION_NAME: "cv-app"
APPDYNAMICS_AGENT_TIER_NAME: "docker-tier"
APPDYNAMICS_CONTROLLER_HOST_NAME: "harness-test.saas.appdynamics.com"
APPDYNAMICS_CONTROLLER_PORT: "443"
APPDYNAMICS_CONTROLLER_SSL_ENABLED: "true"
